Fix build on NetBSD: Solve name clash of TargetArch
Address problem triggered on NetBSD-7.99.26 with GCC 4.8.2

make[1]: stopped in /tmp/pkgsrc-tmp/wip/llilc-git/work/build
/tmp/pkgsrc-tmp/wip/llilc-git/work/llilc/lib/CoreDisTools/coredistools.cpp:58:19:
error: declaration of 'TargetArch CorDisasm::TargetArch' [-fpermissive]
   enum TargetArch TargetArch;
                   ^
In file included from /tmp/pkgsrc-tmp/wip/llilc-git/work/llilc/lib/CoreDisTools/coredistools.cpp:35:0:
/tmp/pkgsrc-tmp/wip/llilc-git/work/llilc/include/CoreDisTools/coredistools.h:36:6:
error: changes meaning of 'TargetArch' from 'enum TargetArch' [-fpermissive]
 enum TargetArch {
      ^